### ISSUE TITLE
Create Client Schema and Tables

### ISSUE THREAD

**Issue by Andyjd86** [Andyjd86/ins-database#5]
Using the shapefile and the imported csv data from the client, link the two together and create the LineStringM geometry.

- [x] Import shp file into database using shp2sql tool. #8 
- [x] Import csv file into new table. #11 
- [x] Write SQL to take client geometry and add it to the imported csv table.
- [x] Using ST_AddMeasure, create a new geometry with LineStringM class. #9 
- [x] Write the SQL as a function to be called by Python with variables.
